export { default as Footer } from "./components/footer/Footer";
export { default as Header } from "./components/header/Header";
export { splashScreen } from "./config/portfolio.config";
export { default as Achievement } from "./sections/achievement/Achievement";
export { default as Blogs } from "./sections/blogs/Blogs";
export { default as Education } from "./sections/education/Education";
export { default as Greeting } from "./sections/greeting/Greeting";
export { default as Podcast } from "./sections/podcast/Podcast";
export { default as ContactProfile } from "./sections/profile/Profile";
export { default as Projects } from "./sections/projects/Projects";
export { default as SkillProgress } from "./sections/skill-progress/SkillProgress";
export { default as Skills } from "./sections/skills/Skills";
export { default as SplashScreen } from "./sections/splash-screen/SplashScreen";
export { default as StartupProjects } from "./sections/startup-projects/StartupProjects";
export { default as Talks } from "./sections/talks/Talks";
export { default as Twitter } from "./sections/twitter/Twitter";
export { default as WorkExperience } from "./sections/work-experience/WorkExperience";
